[package]
name = "lib-raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
env_logger = "0.10.0"
log = "0.4.17"
rand = "0.8.5"
rayon = "1.7.0"
tobj = "4.0.0"
